spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 60s
        ssl:
          useInsecureTrustManager: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - PreserveHostHeader
      routes:
        - id: dynamic-proxy
          predicates:
            - Path=/services/**
          # Bu URI sadece "http" şemasını sağlamak için dummy; filtre gerçek hedefi set edecek
          uri: http://192.108.11.168:8095
          # NOT: StripPrefix kullanma; filter path'i zaten /api/... olarak ayarlıyor
server:
  port: 8088

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
